# Generated by Django 5.2.6 on 2025-10-06 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(default='customer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customers',
                'indexes': [models.Index(fields=['username'], name='customers_usernam_fad06d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['name', 'price'], name='products_name_4f706b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Shopkeepers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(default='shopkeeper', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shopkeepers',
                'indexes': [models.Index(fields=['username'], name='shopkeepers_usernam_2540e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('privileges', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('mode', models.CharField(default='multi', max_length=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_management.customers')),
                ('shopkeeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_management.shopkeepers')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_management.customers')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_management.products')),
            ],
            options={
                'db_table': 'orders',
                'indexes': [models.Index(fields=['customer', 'product'], name='orders_custome_c0f6f7_idx'), models.Index(fields=['order_date'], name='orders_order_d_6e39a9_idx')],
            },
        ),
    ]
