# Generated by Django 5.2.6 on 2025-10-07 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop_management.shopkeepers'),
        ),
    ]
