# Generated by Django 5.2.6 on 2025-10-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0002_products_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsession',
            name='session_id',
            field=models.CharField(default='107f371f-b5c8-428e-8b18-bce29e2d02fc', max_length=64, unique=True),
        ),
    ]
