# Generated by Django 5.2.6 on 2025-10-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0003_alter_customsession_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='customsession',
            name='session_id',
            field=models.CharField(default='243011af-d2f1-4e97-adb5-ef950185dcdc', max_length=64, unique=True),
        ),
    ]
