# Generated by Django 5.2.6 on 2025-10-07 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0004_remove_products_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop_management.shopkeepers'),
        ),
        migrations.AlterField(
            model_name='customsession',
            name='session_id',
            field=models.CharField(default='e7bc5dac-1f8a-4d1b-b366-4e533e0712ca', max_length=64, unique=True),
        ),
    ]
