# Generated by Django 5.2.6 on 2025-10-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0006_categories_remove_customsession_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone_number',
            field=models.CharField(default='9017741946', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customsession',
            name='session_id',
            field=models.CharField(default='890b4b5a-8ae8-4336-961e-f87ad324f032', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='shopkeepers',
            name='phone_number',
            field=models.CharField(default='6663630217', max_length=15, unique=True),
        ),
    ]
