# Generated by Django 5.2.6 on 2025-10-13 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0007_alter_customers_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customsession',
            name='superuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone_number',
            field=models.CharField(default='6872956857', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customsession',
            name='session_id',
            field=models.CharField(default='466eb450-c7c6-408c-9e9d-7a1a08298764', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='shopkeepers',
            name='phone_number',
            field=models.CharField(default='9147849436', max_length=15, unique=True),
        ),
    ]
