# Generated by Django 5.2.6 on 2025-10-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0008_customsession_superuser_alter_customers_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customsession',
            old_name='superuser',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone_number',
            field=models.CharField(default='6842198891', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customsession',
            name='session_id',
            field=models.CharField(default='51602b39-dbcd-4856-85ae-b06e13196b09', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='shopkeepers',
            name='phone_number',
            field=models.CharField(default='7161168930', max_length=15, unique=True),
        ),
    ]
