# Generated by Django 5.2.6 on 2025-10-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0009_rename_superuser_customsession_user_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customers',
            name='customers_usernam_fad06d_idx',
        ),
        migrations.AddField(
            model_name='customers',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='shopkeepers',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone_number',
            field=models.CharField(default='9743894368', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customsession',
            name='session_id',
            field=models.CharField(default='ef565ad9-3713-4f65-a45c-398cf9aa0e8c', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='shopkeepers',
            name='phone_number',
            field=models.CharField(default='8055877277', max_length=15, unique=True),
        ),
        migrations.AddIndex(
            model_name='customers',
            index=models.Index(fields=['username', 'email'], name='customers_usernam_c6437f_idx'),
        ),
    ]
