# Generated by Django 5.2.6 on 2025-10-14 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0010_remove_customers_customers_usernam_fad06d_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='sold_out',
            new_name='total_sold',
        ),
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone_number',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='customsession',
            name='session_id',
            field=models.CharField(default='084edd8a-9eff-4ed8-8658-7f6f0cbf8341', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shopkeepers',
            name='phone_number',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='products',
            unique_together={('name', 'created_by')},
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['category'], name='products_categor_4083ff_idx'),
        ),
    ]
