# Generated by Django 5.2.6 on 2025-10-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0011_rename_sold_out_products_total_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsession',
            name='session_id',
            field=models.CharField(default='837e48d5-500b-4f71-bbfe-5ee16ca729c7', max_length=64, unique=True),
        ),
    ]
