# Generated by Django 5.2.6 on 2025-10-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsession',
            name='session_id',
            field=models.CharField(default='e4b12f38-c2a0-4fc9-bf25-a321091afa1c', max_length=64, unique=True),
        ),
    ]
