# Generated by Django 5.2.6 on 2025-10-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0002_alter_customsession_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsession',
            name='session_id',
            field=models.CharField(default='e1aaafd3-c1cf-4293-9ee0-2b898ec32264', max_length=64, unique=True),
        ),
    ]
