# Generated by Django 5.2.6 on 2025-10-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0003_alter_customsession_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customsession',
            name='session_id',
            field=models.CharField(default='309af670-6948-4eb1-8139-0cea9817f1c4', max_length=64, unique=True),
        ),
    ]
